apiVersion: v1
kind: Service
metadata:
  name: argocd-vpa-updater
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-vpa-updater
spec:
  selector:
    app.kubernetes.io/name: argocd-vpa-updater
  ports:
    - name: http
      port: 8080
      targetPort: http
