apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crds
  - 00-namespace.yaml
  - 01-serviceaccount.yaml
  - 02-clusterrole.yaml
  - 03-role-state.yaml
  - 04-role-repo-creds.yaml
  - 05-state-secret.yaml
  - 06-deployment.yaml
  - 07-service.yaml
