{{- if .Values.ssh.extraKnownHosts }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "argocd-vpa-sync.knownHostsConfigMap" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "argocd-vpa-sync.labels" . | nindent 4 }}
data:
  ssh_known_hosts: |
    {{- .Values.ssh.extraKnownHosts | nindent 4 }}
{{- end }}
