//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoCDApplicationReference) DeepCopyInto(out *ArgoCDApplicationReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoCDApplicationReference.
func (in *ArgoCDApplicationReference) DeepCopy() *ArgoCDApplicationReference {
	if in == nil {
		return nil
	}
	out := new(ArgoCDApplicationReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerWriteBackConfig) DeepCopyInto(out *ContainerWriteBackConfig) {
	*out = *in
	if in.MinChangePercent != nil {
		in, out := &in.MinChangePercent, &out.MinChangePercent
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerWriteBackConfig.
func (in *ContainerWriteBackConfig) DeepCopy() *ContainerWriteBackConfig {
	if in == nil {
		return nil
	}
	out := new(ContainerWriteBackConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VpaGitOpsBinding) DeepCopyInto(out *VpaGitOpsBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VpaGitOpsBinding.
func (in *VpaGitOpsBinding) DeepCopy() *VpaGitOpsBinding {
	if in == nil {
		return nil
	}
	out := new(VpaGitOpsBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VpaGitOpsBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VpaGitOpsBindingList) DeepCopyInto(out *VpaGitOpsBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VpaGitOpsBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VpaGitOpsBindingList.
func (in *VpaGitOpsBindingList) DeepCopy() *VpaGitOpsBindingList {
	if in == nil {
		return nil
	}
	out := new(VpaGitOpsBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VpaGitOpsBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VpaGitOpsBindingSpec) DeepCopyInto(out *VpaGitOpsBindingSpec) {
	*out = *in
	out.VpaRef = in.VpaRef
	if in.ArgoCDApplicationRef != nil {
		in, out := &in.ArgoCDApplicationRef, &out.ArgoCDApplicationRef
		*out = new(ArgoCDApplicationReference)
		**out = **in
	}
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make([]ContainerWriteBackConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VpaGitOpsBindingSpec.
func (in *VpaGitOpsBindingSpec) DeepCopy() *VpaGitOpsBindingSpec {
	if in == nil {
		return nil
	}
	out := new(VpaGitOpsBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VpaGitOpsBindingStatus) DeepCopyInto(out *VpaGitOpsBindingStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VpaGitOpsBindingStatus.
func (in *VpaGitOpsBindingStatus) DeepCopy() *VpaGitOpsBindingStatus {
	if in == nil {
		return nil
	}
	out := new(VpaGitOpsBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VpaReference) DeepCopyInto(out *VpaReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VpaReference.
func (in *VpaReference) DeepCopy() *VpaReference {
	if in == nil {
		return nil
	}
	out := new(VpaReference)
	in.DeepCopyInto(out)
	return out
}
